Feat/#8/find
HanBaeTan42/Study_Ship_Dot-Android_Project pull request #15
Opened 2023-01-22 17:06 UTC by onenewkong

![스크린샷_20230123_123632](https://user-images.githubusercontent.com/100193796/213929446-ac3b8b96-ff60-41a9-ba68-cae3c0c19960.png)

2023-01-22 17:22 UTC, heebum99 requested changes
수정 바랍니다.

2023-01-22 17:22 UTC, heebum99 commented on app/src/main/res/layout/fragment_findid.xml
> +        android:id="@+id/content_background"
line 43: content_background => content_background_findId로 수정

2023-01-22 17:22 UTC, heebum99 commented on app/src/main/res/layout/fragment_findid.xml
> +            android:id="@+id/name_findId"
line 55: name_findId => inputName_findId로 수정

2023-01-22 17:22 UTC, heebum99 commented on app/src/main/res/layout/fragment_findid.xml
> +            android:id="@+id/phnum_findId"
line 68: phnum_findId => inputPn_findId로 수정

2023-01-22 17:38 UTC, heebum99 requested changes

2023-01-22 17:38 UTC, heebum99 commented on app/src/main/res/layout/fragment_findid.xml
> +            android:autoSizeTextType="uniform"
line 34: 불필요한 코드

2023-01-22 18:20 UTC, rvbear commented on app/src/main/res/layout/fragment_findid.xml
> +            android:hint="이름"
(선택사항) line 59: 이름 => @string/name

2023-01-22 18:21 UTC, rvbear commented on app/src/main/res/layout/fragment_findid.xml
>              android:hint="휴대폰 번호"
(선택사항) line 73: 휴대폰 번호 => @string/pn

2023-01-23 06:20 UTC, heebum99 approved these changes

2023-01-23 06:34 UTC, merged

2023-01-23 06:37 UTC, heebum99 commented
아이디 찾기 페이지 디자인 완료